global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-tableau-server
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-tableau-servert1:
    parameter_input: quickstart-tableau-server-example-params1.json
    template_file: quickstart-tableau-server-example1.template
  quickstart-tableau-servert2:
    parameter_input: quickstart-tableau-server-example-params2.json
    template_file: quickstart-tableau-server-example2.template
